version: '3.8'

networks:
  sentryshot_net:
    driver: bridge

services:
  sentryshot:
    build:
      context: .
      dockerfile: Dockerfile
      target: sentryshot
    container_name: sentryshot
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./configs:/app/configs
      - ./storage:/app/storage
      - ./logs:/app/logs
    environment:
      - RUST_LOG=debug
      - TZ=Europe/Moscow
    shm_size: 500m
    command: ["./sentryshot", "run", "--config", "/app/configs/sentryshot.toml"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend
    restart: unless-stopped
    # ИСПРАВЛЕНО: тоже используем host mode
    network_mode: "host"

  mediamtx:
    image: bluenviron/mediamtx:1.3.0
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
    networks:
      - sentryshot_net

  test-camera:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: test-camera
    restart: unless-stopped
    command: >
      -re -f lavfi -i testsrc2=size=1280x720:rate=25 
      -f lavfi -i sine=frequency=1000:sample_rate=48000 
      -c:v libx264 -preset ultrafast -tune zerolatency 
      -c:a aac -b:a 128k -ar 48000
      -f rtsp rtsp://localhost:8554/test
    depends_on:
      - mediamtx
    networks:
      - sentryshot_net